In [20]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

import acquire
import prepare as prep

Work with titanic data to do the following:

In [5]:
titanic = prep.prep_titanic()
titanic

csv file found and loaded


passenger_id  survived  pclass     sex  sibsp  parch     fare embarked  \
0               0         0       3    male      1      0   7.2500        S   
1               1         1       1  female      1      0  71.2833        C   
2               2         1       3  female      0      0   7.9250        S   
3               3         1       1  female      1      0  53.1000        S   
4               4         0       3    male      0      0   8.0500        S   
..            ...       ...     ...     ...    ...    ...      ...      ...   
886           886         0       2    male      0      0  13.0000        S   
887           887         1       1  female      0      0  30.0000        S   
888           888         0       3  female      1      2  23.4500        S   
889           889         1       1    male      0      0  30.0000        C   
890           890         0       3    male      0      0   7.7500        Q   

     alone  sex_male  embarked_Q  embarked_S  
0        0         1           0           1  
1        0         0           0           0  
2        1         0           0           1  
3        0         0           0           1  
4        1         1           0           1  
..     ...       ...         ...         ...  
886      1         1           0           1  
887      1         0           0           1  
888      0         0           0           1  
889      1         1           0           0  
890      1         1           1           0  

[891 rows x 12 columns]

In [6]:
df = prep.split_data(titanic, 'survived')
df

(     passenger_id  survived  pclass     sex  sibsp  parch      fare embarked  \
 455           455         1       3    male      0      0    7.8958        C   
 380           380         1       1  female      0      0  227.5250        C   
 492           492         0       1    male      0      0   30.5000        S   
 55             55         1       1    male      0      0   35.5000        S   
 243           243         0       3    male      0      0    7.1250        S   
 ..            ...       ...     ...     ...    ...    ...       ...      ...   
 695           695         0       2    male      0      0   13.5000        S   
 128           128         1       3  female      1      1   22.3583        C   
 636           636         0       3    male      0      0    7.9250        S   
 222           222         0       3    male      0      0    8.0500        S   
 496           496         1       1  female      1      0   78.2667        C   
 
      alone  sex_male  emb

In [7]:
train,validate,test = df
train

passenger_id  survived  pclass     sex  sibsp  parch      fare embarked  \
455           455         1       3    male      0      0    7.8958        C   
380           380         1       1  female      0      0  227.5250        C   
492           492         0       1    male      0      0   30.5000        S   
55             55         1       1    male      0      0   35.5000        S   
243           243         0       3    male      0      0    7.1250        S   
..            ...       ...     ...     ...    ...    ...       ...      ...   
695           695         0       2    male      0      0   13.5000        S   
128           128         1       3  female      1      1   22.3583        C   
636           636         0       3    male      0      0    7.9250        S   
222           222         0       3    male      0      0    8.0500        S   
496           496         1       1  female      1      0   78.2667        C   

     alone  sex_male  embarked_Q  embarked_S  
455      1         1           0           0  
380      1         0           0           0  
492      1         1           0           1  
55       1         1           0           1  
243      1         1           0           1  
..     ...       ...         ...         ...  
695      1         1           0           1  
128      0         0           0           0  
636      1         1           0           1  
222      1         1           0           1  
496      0         0           0           0  

[534 rows x 12 columns]

In [8]:
train = train.drop(columns=['sex'])
validate = validate.drop(columns=['sex'])
test = test.drop(columns=['sex'])
train

passenger_id  survived  pclass  sibsp  parch      fare embarked  alone  \
455           455         1       3      0      0    7.8958        C      1   
380           380         1       1      0      0  227.5250        C      1   
492           492         0       1      0      0   30.5000        S      1   
55             55         1       1      0      0   35.5000        S      1   
243           243         0       3      0      0    7.1250        S      1   
..            ...       ...     ...    ...    ...       ...      ...    ...   
695           695         0       2      0      0   13.5000        S      1   
128           128         1       3      1      1   22.3583        C      0   
636           636         0       3      0      0    7.9250        S      1   
222           222         0       3      0      0    8.0500        S      1   
496           496         1       1      1      0   78.2667        C      0   

     sex_male  embarked_Q  embarked_S  
455         1           0           0  
380         0           0           0  
492         1           0           1  
55          1           0           1  
243         1           0           1  
..        ...         ...         ...  
695         1           0           1  
128         0           0           0  
636         1           0           1  
222         1           0           1  
496         0           0           0  

[534 rows x 11 columns]

In [9]:
train = train.drop(columns=['embarked'])
validate = validate.drop(columns=['embarked'])
test = test.drop(columns=['embarked'])
train

passenger_id  survived  pclass  sibsp  parch      fare  alone  sex_male  \
455           455         1       3      0      0    7.8958      1         1   
380           380         1       1      0      0  227.5250      1         0   
492           492         0       1      0      0   30.5000      1         1   
55             55         1       1      0      0   35.5000      1         1   
243           243         0       3      0      0    7.1250      1         1   
..            ...       ...     ...    ...    ...       ...    ...       ...   
695           695         0       2      0      0   13.5000      1         1   
128           128         1       3      1      1   22.3583      0         0   
636           636         0       3      0      0    7.9250      1         1   
222           222         0       3      0      0    8.0500      1         1   
496           496         1       1      1      0   78.2667      0         0   

     embarked_Q  embarked_S  
455           0           0  
380           0           0  
492           0           1  
55            0           1  
243           0           1  
..          ...         ...  
695           0           1  
128           0           0  
636           0           1  
222           0           1  
496           0           0  

[534 rows x 10 columns]

In [10]:
train.head()

passenger_id  survived  pclass  sibsp  parch      fare  alone  sex_male  \
455           455         1       3      0      0    7.8958      1         1   
380           380         1       1      0      0  227.5250      1         0   
492           492         0       1      0      0   30.5000      1         1   
55             55         1       1      0      0   35.5000      1         1   
243           243         0       3      0      0    7.1250      1         1   

     embarked_Q  embarked_S  
455           0           0  
380           0           0  
492           0           1  
55            0           1  
243           0           1

In [11]:
X_train = train.iloc[:,2:]
X_train


pclass  sibsp  parch      fare  alone  sex_male  embarked_Q  embarked_S
455       3      0      0    7.8958      1         1           0           0
380       1      0      0  227.5250      1         0           0           0
492       1      0      0   30.5000      1         1           0           1
55        1      0      0   35.5000      1         1           0           1
243       3      0      0    7.1250      1         1           0           1
..      ...    ...    ...       ...    ...       ...         ...         ...
695       2      0      0   13.5000      1         1           0           1
128       3      1      1   22.3583      0         0           0           0
636       3      0      0    7.9250      1         1           0           1
222       3      0      0    8.0500      1         1           0           1
496       1      1      0   78.2667      0         0           0           0

[534 rows x 8 columns]

In [12]:
X_validate = validate.iloc[:,2:]
X_validate


pclass  sibsp  parch     fare  alone  sex_male  embarked_Q  embarked_S
176       3      3      1  25.4667      0         1           0           1
372       3      0      0   8.0500      1         1           0           1
678       3      1      6  46.9000      0         0           0           1
778       3      0      0   7.7375      1         1           1           0
463       2      0      0  13.0000      1         1           0           1
..      ...    ...    ...      ...    ...       ...         ...         ...
622       3      1      1  15.7417      0         1           0           0
302       3      0      0   0.0000      1         1           0           1
518       2      1      0  26.0000      0         0           0           1
765       1      1      0  77.9583      0         0           0           1
837       3      0      0   8.0500      1         1           0           1

[178 rows x 8 columns]

In [13]:
X_test = test.iloc[:,2:]
X_test

pclass  sibsp  parch      fare  alone  sex_male  embarked_Q  embarked_S
561       3      0      0    7.8958      1         1           0           1
641       1      0      0   69.3000      1         0           0           0
400       3      0      0    7.9250      1         1           0           1
498       1      1      2  151.5500      0         0           0           1
875       3      0      0    7.2250      1         0           0           0
..      ...    ...    ...       ...    ...       ...         ...         ...
339       1      0      0   35.5000      1         1           0           1
841       2      0      0   10.5000      1         1           0           1
442       3      1      0    7.7750      0         1           0           1
815       1      0      0    0.0000      1         1           0           1
53        2      1      0   26.0000      0         0           0           1

[179 rows x 8 columns]

In [14]:
target = 'survived'

In [15]:
y_train = train[target]
y_train

455    1
380    1
492    0
55     1
243    0
      ..
695    0
128    1
636    0
222    0
496    1
Name: survived, Length: 534, dtype: int64

In [16]:
y_validate = validate[target]
y_validate

176    0
372    0
678    0
778    0
463    0
      ..
622    1
302    0
518    1
765    1
837    0
Name: survived, Length: 178, dtype: int64

In [17]:
y_test = test[target]
y_test

561    0
641    1
400    1
498    0
875    1
      ..
339    0
841    0
442    0
815    0
53     1
Name: survived, Length: 179, dtype: int64

In [18]:
train.survived.value_counts()

0    329
1    205
Name: survived, dtype: int64

In [19]:
(train.survived == 0).mean()

0.6161048689138576

Fit the Random Forest classifier to your training sample and transform (i.e. make predictions on the training sample) setting the random_state accordingly and setting min_samples_leaf = 1 and max_depth = 10.

In [24]:
rf = RandomForestClassifier(min_samples_leaf = 1, max_depth = 10)
rf

RandomForestClassifier(max_depth=10)

In [25]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10)

In [27]:
rf.predict(X_train)

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [28]:
rf.predict_proba(X_train)[:5]

array([[0.76388633, 0.23611367],
       [0.        , 1.        ],
       [0.56311215, 0.43688785],
       [0.28627386, 0.71372614],
       [0.98810006, 0.01189994]])

In [26]:
rf.score(X_train, y_train)

0.9438202247191011

Evaluate your results using the model score, confusion matrix, and classification report.



In [29]:
rf.score(X_train, y_train)

0.9438202247191011

In [30]:
y_pred = rf.predict(X_train)
y_pred[:5]

array([0, 1, 0, 1, 0])

In [31]:
conf = confusion_matrix(y_train, y_pred)
conf

array([[324,   5],
       [ 25, 180]])

In [33]:
labels = sorted(y_train.unique())
labels

[0, 1]

In [35]:
pd.DataFrame(conf,
            index=[str(label) + '_actual'for label in labels],
            columns=[str(label) + '_predict'for label in labels])

0_predict  1_predict
0_actual        324          5
1_actual         25        180

Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

In [49]:
# Survived = positive
TP = 180
TN = 324
FP = 5
FN = 25

acc = (TP+TN)/(TP+TN+FP+FN)
total = (TP+TN+FP+FN)
true_positive_rate = TP/(total)
false_positive_rate = FP/(total)
true_negative_rate = TN/(total)
false_negative_rate = FN/(total)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
f1_score = (2 * (precision * recall) / (precision + recall))
support_pos = FN + TP
support_neg = TN + FP

print('acc =',acc)
print('true positive rate =',true_positive_rate) 
print('true negative rate =', true_negative_rate)
print('false positive rate =', false_positive_rate)
print('false negative rate =', false_negative_rate)
print('precision =',precision)
print('recall =',recall)
print('f1 score =', f1_score)
print('positive support =', support_pos)
print('negative support =', support_neg)

acc = 0.9438202247191011
true positive rate = 0.33707865168539325
true negative rate = 0.6067415730337079
false positive rate = 0.009363295880149813
false negative rate = 0.04681647940074907
precision = 0.972972972972973
recall = 0.8780487804878049
f1 score = 0.923076923076923
positive support = 205
negative support = 329


Run through steps increasing your min_samples_leaf and decreasing your max_depth

In [54]:
rf = RandomForestClassifier(min_samples_leaf = 1, max_depth = 10)
rf.fit(X_train, y_train)
rf.score(X_train, y_train)

0.9438202247191011

In [50]:
rf1 = RandomForestClassifier(min_samples_leaf = 2, max_depth = 9)
rf1.fit(X_train, y_train)
rf1.score(X_train, y_train)

0.8913857677902621

In [51]:
rf2 = RandomForestClassifier(min_samples_leaf = 3, max_depth = 8)
rf2.fit(X_train, y_train)
rf2.score(X_train, y_train)

0.8764044943820225

In [52]:
rf3 = RandomForestClassifier(min_samples_leaf = 4, max_depth = 7)
rf3.fit(X_train, y_train)
rf3.score(X_train, y_train)

0.8576779026217228

In [53]:
rf4 = RandomForestClassifier(min_samples_leaf = 5, max_depth = 6)
rf4.fit(X_train, y_train)
rf4.score(X_train, y_train)

0.8520599250936329

What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?
- model 4 has a lower accuracy at .85 however the difference between the train and validate is the smallest with 
    - a difference of 0.048689138576779034

In [61]:
rf.score(X_train, y_train)

0.9438202247191011

In [56]:

rf.score(X_validate, y_validate)

0.7584269662921348

In [66]:
(rf.score(X_train, y_train))-(rf.score(X_validate, y_validate))

0.1853932584269663

-difference 0.1853932584269663

In [67]:


rf1.score(X_train, y_train)

0.8913857677902621

In [57]:
rf1.score(X_validate, y_validate)

0.7752808988764045

In [68]:
(rf1.score(X_train, y_train))-(rf1.score(X_validate, y_validate))

0.11610486891385763

- difference 0.11610486891385763

In [63]:
rf2.score(X_train, y_train)

0.8764044943820225

In [58]:
rf2.score(X_validate, y_validate)

0.8033707865168539

In [69]:
(rf2.score(X_train, y_train))-(rf2.score(X_validate, y_validate))

0.0730337078651686

- difference 0.0730337078651686

In [64]:
rf3.score(X_train, y_train)

0.8576779026217228

In [59]:
rf3.score(X_validate, y_validate)

0.797752808988764

In [71]:
(rf3.score(X_train, y_train))-(rf3.score(X_validate, y_validate))

0.05992509363295884

- difference 0.05992509363295884

In [65]:
rf4.score(X_train, y_train)

0.8520599250936329

In [60]:
rf4.score(X_validate, y_validate)

0.8033707865168539

In [72]:
(rf4.score(X_train, y_train))-(rf4.score(X_validate, y_validate))

0.048689138576779034

- difference 0.048689138576779034

After making a few models, which one has the best performance (or closest metrics) on both train and validate?

- my rf4 performs the best